name: flutter_html_all
description: All optional flutter_html widgets, bundled into a single package.
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html:
    git:
      url: https://github.com/tienbm/flutter_html.git
  flutter_html_audio:
    git:
      url: https://github.com/tienbm/flutter_html.git
      path: packages/flutter_html_audio
  flutter_html_iframe:
    git:
      url: https://github.com/tienbm/flutter_html.git
      path: packages/flutter_html_iframe
  flutter_html_math:
    git:
      url: https://github.com/tienbm/flutter_html.git
      path: packages/flutter_html_math
  flutter_html_svg:
    git:
      url: https://github.com/tienbm/flutter_html.git
      path: packages/flutter_html_svg
  flutter_html_table:
    git:
      url: https://github.com/tienbm/flutter_html.git
      path: packages/flutter_html_table
  flutter_html_video:
    git:
      url: https://github.com/tienbm/flutter_html.git
      path: packages/flutter_html_video

      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - css
  - widgets
  - layout
